COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
  PATCH_IF NOT ENGINE_IS ~bgee bg2ee eet iwdee pstee~ BEGIN // I think innate bcs crash is fixed in EE
    PATCH_INCLUDE ~%comp_dir%/innate_to_level_1.tpp~
  END
  PATCH_INCLUDE ~%comp_dir%/slot_and_ability_target.tpp~
  PATCH_INCLUDE ~%comp_dir%/fix_effect_target.tpp~
BUT_ONLY

PATCH_IF NOT ENGINE_IS ~bgee bg2ee eet iwdee pstee~ BEGIN
  INCLUDE ~%comp_dir%/fix_bcs_innate.tpa~
END
