ACTION_DEFINE_ASSOCIATIVE_ARRAY opcode_with_res BEGIN
  67  => ~cre~
  135 => ~cre~
  151 => ~cre~
  168 => ~cre~

  111 => ~itm~
  112 => ~itm~
  122 => ~itm~
  143 => ~itm~

  146 => ~spl~
  147 => ~spl~
  148 => ~spl~
  171 => ~spl~
  172 => ~spl~
  206 => ~spl~
  207 => ~spl~
  232 => ~spl~
  266 => ~spl~

  152 => ~mve~

  174 => ~wav~

  107 => ~bmp~

  177 => ~eff~
  248 => ~eff~
  249 => ~eff~

  186 => ~are~
END
