OUTER_SET existence_fix = 0
ACTION_IF (FILE_EXISTS "TobEx_ini/TobExCore.ini") AND (FILE_CONTAINS "TobEx_ini/TobExCore.ini" "Existence Sound Fix=1") BEGIN
  PRINT "ToBEx Existence Sound Fix is set! Shifting creature EXISTANCE sounds where applicable..."
  OUTER_SET existence_fix = 1
  COPY_EXISTING ~PDIALOG.2DA~ ~override~
    PRETTY_PRINT_2DA
  BUT_ONLY
END

COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
  PATCH_INCLUDE ~%comp_dir%/init_fix.tpp~
BUT_ONLY
