COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
/*    PATCH_INCLUDE ~%comp_dir%/add_missing_animation.tpp~
    PATCH_INCLUDE ~%comp_dir%/remove_missing_scripts.tpp~
    PATCH_INCLUDE ~%comp_dir%/remove_missing_dialogs.tpp~
    PATCH_INCLUDE ~%comp_dir%/fix_spells.tpp~
    PATCH_INCLUDE ~%comp_dir%/null_sounds.tpp~ */
    PATCH_INCLUDE ~%comp_dir%/remove_useless_effects.tpp~
  END
BUT_ONLY
