// BG2Fixpack BETA Core fixes causing self-inflicting burns on flaming swords and miscellany
ACTION_IF !(FILE_EXISTS_IN_GAME ~cdhalb04.eff~) BEGIN
  COPY_EXISTING ~dragdam3.eff~ ~override/cdhalb04.eff~
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~cdsw1h03.eff~) BEGIN
  COPY_EXISTING ~lycandam.eff~ ~override/cdsw1h03.eff~
END

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_INCLUDE ~%comp_dir%/bg2fixpack.tpp~
BUT_ONLY
